### ISSUE TITLE
ZERO Downtime

### ISSUE THREAD

**Issue by jankapunkt** [eduhack/leaonline-meteor-passenger#3]
https://www.phusionpassenger.com/library/deploy/nginx/zero_downtime_redeployments/meteor/

**Comment by aakalaew** [comment]
First of all you install Passanger

```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
sudo apt-get install -y apt-transport-https ca-certificates


sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main > /etc/apt/sources.list.d/passenger.list'
sudo apt-get update


sudo apt-get install -y passenger
```

**Comment by aakalaew** [comment]
To validate your installation run following code `passanger-config validate-install`

**Comment by aakalaew** [comment]
To enable the zero-downtime restarts on your application, you need to paste this argument `--rolling-restart` in this line `RESTART_ARGS=`. You will find the argument in your file you created before `deploy/work.sh`

**Comment by aakalaew** [comment]
To track your zero downtime restarts you can use the command `passenger-status`
